### ISSUE TITLE
Is your organization and of the types of centralization correct?

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#31] opened 2022-04-08 06:01 UTC
You discuss direct, indirect, inherited, and platform centralization.  Is this model the appropriate delineation?  Is there more direct language you can use to describe these forms?

**Comment by elear** [comment] 2022-04-08 06:05
The purpose of this question is not to claim that you are wrong or that I know of a better model.  Rather, I'd suggest that you do two things here:

 - take a step back and think about whether there are other organizations of your thoughts that might bring your point across in a clearer crisper way.
  - use of "direct" and "indirect" is... indirect.  You might want to consider more descriptive terms.

N.B.: class this "minor issue or question"

**Comment by mnot** [comment] 2022-05-15 04:51
I think the classification as it sits serves the immediate purpose -- informing a discussion of what an SDO (specifically, the IETF) can and cannot do about centralization. Very happy to consider other arrangements or even specific issues with this classification.

Re: direct/indirect -- yeah, I'm not 100% happy with these names (and perhaps others). 

For "direct", how about "Centralization by Design" or "Intentional Centralization"? Other ideas?

For "indirect", how about "Centralisation by Side Effect" or "Induced Centralization"? Other ideas?

**Comment by elear** [comment] 2022-05-15 07:42
Must noodle further.  This may be one you might want to ask people **other** than me.  Perhaps there is a term of art that an economist could cough up.

**Comment by mnot** [comment] 2022-05-15 08:32
Maybe we should just call it 'monopolistic' instead of 'direct', then.

**Comment by mnot** [comment] 2022-05-15 08:33
... and maybe 'market-driven' instead of 'indirect'?

**Comment by mnot** [comment] 2022-05-15 09:49
If 'monopolistic' has too many legal overtones/implications (which we *can* caution against), perhaps just 'fixed centralization'.

**Comment by mnot** [comment] 2022-05-15 22:27
'proprietary' seems like a better fit and less potentially problematic.

**Comment by elear** [comment] 2022-05-16 06:58
This probably rambles a bit.  Take it as you will...

Proprietary Protocols is a good way of putting this, and it jibes very well with what Europe is saying right now.  What is the benefit to the protocol "owner"/developer?

 - Only those who the "owner" authorizes can even see the specification, much less implement it.
 - If the owner controls both ends, they can retire old protocol features or correct bugs without having to go through a laborious standards process.
 - New features can be rapidly introduced.

In fact, MOST protocols these days are proprietary.  Any app on a phone or tablet has such a thing, and it is often No Big Deal.  What makes it A Big Deal?  There's some other aspect that triggers centralization.

**Comment by mnot** [comment] 2022-05-22 03:18
changed 'indirect' to 'concentration'. A tiny bit awkward from a 'does this fit with the others', but really really nice from a high level, I think.

**Comment by mnot** [comment] 2022-05-22 03:21
I think the edits above address everything here (although some of it could be expanded upon). Am closing, feel free to continue to discuss or request reopening if I didn't.

**Closed by mnot** 2022-05-22 03:21 UTC
Labels: work item
