### ISSUE TITLE
Section 4.5 on intermediates

### ISSUE THREAD

**Issue by mirjak** [mnot/avoiding-internet-centralization#62] opened 2022-09-05 15:56 UTC
I’m not sure I follow or agree to section 5.4:

> However, introducing a new party to communication adds concentration
>    and platform centralization risk to Internet protocols, because it
>    brings opportunities for control and observation.

i would actually think that distributing control to more entities can help to avoid centralization…

I think the text makes some good points about the pros and cons of intermediates, I’m not sure I fully understand the relation to centralization. Maybe this is just a separate topic…?

**Comment by mnot** [comment] 2022-11-25 05:11
This section has been broadened from 'intermediation' to 'delegation of power', which I think might address your concern. The issue is when you give more parties control over communication - _not_ when you give users the ability to choose who has access to communication.

Closing, but if you disagree / want to talk more, please say so.

**Closed by mnot** 2022-11-25 05:11 UTC
Labels: work item
